<template>
  <button
    type="button"
    class="
    p-3
    rounded-sm
    text-pink-50
    bg-blue-500
    active:shadow-sm
    active:bg-pink-800
    transition-colors
    transition-shadows
    duration-500
    ease-linear
    ">Hellow</button>
</template>